### ISSUE TITLE
Metashape XML doesnt match images

### ISSUE THREAD

**Issue by jeffreyianwilson** [facebookresearch/EyefulTower#2]
Metashape XML camera poses do not match images so I cannot evaluate/recreate the rig in Metashape.  Any chance the full resolution images could be made available?

**Comment by cr333** [comment]
The full-resolution images we used for Metashape are already available in the `images-jpeg` subdirectories of each scene.

See the column labelled "8K+ JPEGs" in the [dataset overview table](https://github.com/facebookresearch/EyefulTower#dataset-overview).
