### ISSUE TITLE
How to import cameras.xml and 2K images into metashape?

### ISSUE THREAD

**Issue by HrsPythonix** [facebookresearch/EyefulTower#4]
As title, I want to import the provided cameras.xml and 2K images into metashape, is that possible?

**Comment by cr333** [comment]
This should be possible if you rescale the camera intrinsics to match the new image resolution before the import.

Specifically, you will need to update the following values for all `<sensor>`s:
* `<resolution width="5784" height="8660"/>`
* under `<calibration>`: `<f>` (focal length), `<cx>` and `<cy>` (principal point)

I don't think these values need updating, but you might as well, for consistency:
```
<property name="pixel_width" value="0.0041666699999999999"/>
<property name="pixel_height" value="0.0041666699999999999"/>
```

Hope this works for you. Please report back.

**Comment by HrsPythonix** [comment]
> This should be possible if you rescale the camera intrinsics to match the new image resolution before the import.
> 
> Specifically, you will need to update the following values for all `<sensor>`s:
> 
> * `<resolution width="5784" height="8660"/>`
> * under `<calibration>`: `<f>` (focal length), `<cx>` and `<cy>` (principal point)
> 
> I don't think these values need updating, but you might as well, for consistency:
> 
> ```
> <property name="pixel_width" value="0.0041666699999999999"/>
> <property name="pixel_height" value="0.0041666699999999999"/>
> ```
> 
> Hope this works for you. Please report back.

Thanks, I'll give it a try and report later.

**Comment by HrsPythonix** [comment]
> This should be possible if you rescale the camera intrinsics to match the new image resolution before the import.
> 
> Specifically, you will need to update the following values for all `<sensor>`s:
> 
> * `<resolution width="5784" height="8660"/>`
> * under `<calibration>`: `<f>` (focal length), `<cx>` and `<cy>` (principal point)
> 
> I don't think these values need updating, but you might as well, for consistency:
> 
> ```
> <property name="pixel_width" value="0.0041666699999999999"/>
> <property name="pixel_height" value="0.0041666699999999999"/>
> ```
> 
> Hope this works for you. Please report back.

Modifying all `<resolution width="5784" height="8660"/>` to `<resolution width="1368" height="2048"/>`
and
scale all `<f>`, `<cx>`, `<cy>` by 4.228515625 (2048 / 8660). Without updating `pixel_width` and `pixel_width`

The result look like below, seems resonable.

![image](https://github.com/facebookresearch/EyefulTower/assets/16586180/ac5f9228-a29d-4592-b73a-368373d96cce)
