### ISSUE TITLE
Looking for EXR metadata

### ISSUE THREAD

**Issue by pooraniravi** [facebookresearch/EyefulTower#6]
Hi,

Based on RAWNerf, I wanted to know to get metadata (like WhiteLevel -BlackLevel -AsShotNeutral -ColorMatrix2 -ShutterSpeed) to convert HDR to LDR sRGB space. But, I do not see any of this metadata using OpenEXR. Can you share more information on how you converted your EXR images to Srgb space or how to extract these meta fields?

**Comment by cr333** [comment]
As far as I know, the EXR format does not support storing any of the metadata you ask for.

We create the HDR images using libraw's `dcraw_emu` tool using arguments `-T -4 -o 7`, i.e. the output are 16-bit linear TIFF images in the DCI-P3 color space, which we merge in the same linear color space. You can assume the black level is 0.

The original raw images have shutter speeds between 1/25 and 1/200 seconds (+/–4 stops for the exposure bracket), but the final EXRs are brightened by 1 to 3 stops to equalise the brightness across scenes.

We convert our EXR images to sRGB using the code provided in the readme: [Example code: reading EXR images to create JPEGs
](https://github.com/facebookresearch/EyefulTower?tab=readme-ov-file#example-code-reading-exr-images-to-create-jpegs)

If you need more specific detail, could you please include a short description of what you need it for?
