### ISSUE TITLE
Colmap format for camera poses

### ISSUE THREAD

**Issue by huguensjean** [facebookresearch/EyefulTower#7]
Any chance we could get a script that converts these poses to colmap format?
[cameras.json](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/EyefulTower/apartment/cameras.json)
[cameras.xml](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/EyefulTower/apartment/cameras.xml)

**Comment by cr333** [comment]
Could you please elaborate a bit? Why would like to have the poses in COLMAP format?

**Comment by huguensjean** [comment]
I'm using this ZipNeRF pipeline to recreate the scenes:
https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_camp_zipnerf.ipynb

It takes up 20 hours to get the camera poses. Having the poses in COLMAP plays well with our current dataloader.

To be clear, in COLMAP,

cameras.txt: This file will contain the camera intrinsics. In the provided JSON or XML, camera intrinsics are given by the K matrix.

images.txt: This file will contain extrinsics (rotation, translation) and other information for each image. The rotation and translation can be derived from the T matrices. The T matrix combines rotation and translation, where the first three columns represent the rotation and the fourth column represents the translation. The image name can be derived from cameraId.

points3D.txt: We do not use this file.

We do a decent job with v2,
![RWtCT4E4bEPwrUb](https://github.com/facebookresearch/EyefulTower/assets/40362353/732c2593-ab16-4fce-a618-c9e65d2d14f2)

but we struggle with v1,
https://github.com/facebookresearch/EyefulTower/assets/40362353/58e2f37e-2e45-4a77-b590-8b521b98a33e

Loading your poses will most likely solve this issue.

**Comment by huguensjean** [comment]
Hello @cr333, am I asking for too much? We updated our NeRF [notebook]
(https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/model_garden/model_garden_camp_zipnerf.ipynb).

We recently added [fisheye](https://github.com/rmbrualla/pycolmap/blob/master/pycolmap/camera.py) camera support for colmap.

In the distortion model:
![unnamed-1](https://github.com/facebookresearch/EyefulTower/assets/40362353/3fc23b30-0986-441a-87bb-395f0d0721d3)

That suggests you might need to set the COLMAP camera type to SIMPLE_RADIAL, RADIAL, OPENCV, or FULL_OPENCV. We tried. Waste of time. I really think SIFT is messing up the poses. Colmap matching is failing somewhere for fisheye pictures.

How do get camera.json? Could you provide directions on how to convert to colmap?

**Comment by cr333** [comment]
Thank you so much for your efforts on converting our camera poses and intrinsics to COLMAP. We agree that this would make our dataset even more accessible (beyond the support we already added to Nerfstudio), so we are very much interested in figuring this out! I'm sorry that we didn't have the bandwidth to respond properly yet.

We create the `cameras.json` using an internal script that loads Metashape's `cameras.xml` and exports it to [the format we documented in the ReadMe](https://github.com/facebookresearch/EyefulTower?tab=readme-ov-file#camera-calibration-in-krt-format-camerasjson).

Looking at COLMAP's source code, it seems like the `OPENCV_FISHEYE` model only supports 4 distortion parameters (`k1, k2, k3, k4`) while our fisheye distortion needs the full 8-parameter model (`k1, k2, k3, _, _, _, p1, p2`), including tangential distortion (`p1, p2`):
https://github.com/colmap/colmap/blob/release/3.9/src/colmap/sensor/models.h#L271-L279

FYI, The [`THIN_PRISM_FISHEYE` model in COLMAP](https://github.com/colmap/colmap/blob/release/3.9/src/colmap/sensor/models.h#L357-L373) has parameters with all the right names (`fx, fy, cx, cy, k1, k2, p1, p2, k3, k4, sx1, sy1`), so you might be able to adapt it by setting the other parameters to zero or some other value.

Failing that, you could also first undistort the fisheye images using `cv2.undistort`. This creates ideal (equidistant) fisheye images, which you should then be able to use with any of the supported fisheye models and zero lens distortion. This is what we do in our VR-NeRF implementation.

Hope this helps. I would be grateful if you could report back, so we can add COLMAP support to our dataset.

**Comment by m-mousatat** [comment]
is there any new update how to get the colmap format of this dataset?

**Comment by yiduohao** [comment]
Hi, thanks for all your hard work! Is there any update on the colmap version of this dataset? I am trying to use this dataset (raf_furnishedroom) on 3DGS, and it would be really helpful if a colmap format is release. Thanks.

**Comment by cr333** [comment]
Thanks for asking. I wrote an internal conversion script that exports the Metashape reconstructions of our datasets to COLMAP. Unfortunately, I didn't have time to finish this; I will try to find some time to export our models in the next week or two, and would highly appreciate if someone could test them.

**Comment by cr333** [comment]
Thank you for your patience, everyone. I just uploaded COLMAP reconstructions in the `colmap` directory for each scene.

The format is the same as for Mip-NeRF 360, so it is compatible with [gsplat](https://github.com/nerfstudio-project/gsplat), for example.

I tried all scenes using the MCMC flavor of gsplat 1.14 and all started training well, but most scenes collapsed after about 4,000 iterations. I don't have time to debug this, though.

`office_view2`, `riverview`, `seating_area` and `table` trained to convergence with the following command:
`python simple_trainer.py mcmc --no-normalize-world-space --eval_steps -1 --data_factor 8 --strategy.cap-max 1000000 --render_traj_path ellipse --data_dir $DATASET/colmap --result_dir $DATASET/gsplat_mcmc_8`

Please let us know if you find any issues.

**Comment by cr333** [comment]
PS: All 13 scenes reconstruct reasonably well with gsplat 1.14 using the `default` training strategy at 1/8 resolution:
```
python simple_trainer.py default --no-normalize-world-space --eval_steps -1 --data_factor 8 --render_traj_path ellipse --data_dir $DATASET/colmap --result_dir $DATASET/gsplat_default_8
```

**Comment by huguensjean** [comment]
Thank you for the update and sharing the dataset. I haven't tried all the scenes yet, but here's a reconstruction of one of the office scenes with the colmap data you shared.

https://github.com/user-attachments/assets/8ee9090a-ffa0-4650-825c-0e3522fa1c33

**Comment by cr333** [comment]
@huguensjean, I'm glad it worked for you and looks pretty good! :)

**Comment by Yang-Xijie** [comment]
https://github.com/facebookresearch/EyefulTower/issues/7#issuecomment-2021722849

> We create the cameras.json using an internal script that loads Metashape's cameras.xml and exports it to [the format we documented in the ReadMe](https://github.com/facebookresearch/EyefulTower?tab=readme-ov-file#camera-calibration-in-krt-format-camerasjson).

Could you please share this internal script?

---

I found that the `p1, p2` in `cameras.xml` are interchanged in `cameras.json`. Is this by design?


https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/EyefulTower/apartment/cameras.json

L23-L31

```
      "distortion": [
        -0.03823023528744702,  # k1
        0.011062009972943147,  # k2
        -0.0004975289812637742,  # p1 (here)
        0.0002160237193391678,  # p2 (here)
        -0.0009125422794027956  # k3
      ],
      "distortionModel": "RadialAndTangential",
      "cameraId": "10/10_DSC0001",
```

https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/EyefulTower/apartment/cameras.xml

L5-L27

```
      <sensor id="0" label="Camera 0" type="frame">
        <resolution width="5784" height="8660"/>
        <property name="pixel_width" value="0.0041666699999999999"/>
        <property name="pixel_height" value="0.0041666699999999999"/>
        <property name="focal_length" value="12"/>
        <property name="layer_index" value="0"/>
        <bands>
          <band label="Red"/>
          <band label="Green"/>
          <band label="Blue"/>
        </bands>
        <data_type>uint8</data_type>
        <calibration type="frame" class="adjusted">
          <resolution width="5784" height="8660"/>
          <f>2960.5102118128075</f>
          <cx>-17.560509659766243</cx>
          <cy>-15.527905611307846</cy>
          <k1>-0.038230235287447019</k1>
          <k2>0.011062009972943147</k2>
          <k3>-0.00091254227940279562</k3>
          <p1>0.0002160237193391678</p1>  # (here)
          <p2>-0.00049752898126377424</p2>  # (here)
        </calibration>
```

Besides, it seems that p1 and p2 are relatively small that interchanging them make no big difference.

**Comment by cr333** [comment]
The swapped `p1` and `p2` is due different conventions used by OpenCV and Metashape.

OpenCV uses `p1` for weighting _x'y'_ in _x''_, and `p2` for weighting _x'y'_ in _y''_ ([see documentation](https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html#:~:text=pinhole%20camera%20model.-,Pinhole%20camera%20model,-Real%20lenses%20usually)):
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/a13f9b1a-9bfa-4335-948a-e6f4457d707d" />

Metashape uses `p2` for weighting _x'y'_ in _x''_, and `p1` for weighting _x'y'_ in _y''_ ([see documentation](https://www.agisoft.com/pdf/metashape-pro_2_2_en.pdf#page=246):
<img width="500" alt="Image" src="https://github.com/user-attachments/assets/0623ca37-dace-4fe8-abfb-61956957157b" />

The [documentation for our `cameras.json`](https://github.com/facebookresearch/EyefulTower?tab=readme-ov-file#camera-calibration-in-krt-format-camerasjson) is correct: the distortion coefficients use the same order as OpenCV.

**Comment by Yang-Xijie** [comment]
> Thank you for the update and sharing the dataset. I haven't tried all the scenes yet, but here's a reconstruction of one of the office scenes with the colmap data you shared.
> 
>  checkpoints_office1b_path_renders_step_25000_color.mp4

Hi, I am curious about the reconstruction method you adopted to derive such high-quality results. Did you directly run ZipNeRF on the provided COLMAP dataset of office1b? And did you add something else to help the reconstruction (such as vignetting modeling)?

I tried running gsplat (https://docs.gsplat.studio/main/examples/colmap.html) on offfice1b, but the reconstruction result seems like, a room filled with fog 🌫️
