### ISSUE TITLE
FovX and FovY

### ISSUE THREAD

**Issue by Ahmedhasssan** [facebookresearch/EyefulTower#8]
Hi, 

I have 2 questions.

1. For JPEG-1K datasets, what are the FovX and FovY? I am following the conventional NeRF Blender scheme to prepare my dataloader. If there is a better way to prepare the dataloader please guide me.

2. To extract the Rotation matrix (T) and Translation vector (T), can I directly use R=np.transpose(cameras.json['T'])[:3,:3] and T= np.transpose(cameras.json['T'])[:3,3]? Since your T matrix is world-to-camera matix.

Please correct me if I am wrong in question 2.

Thanks

**Comment by cr333** [comment]
1. FovX and FovY are usually only used for synthetic datasets like the NeRF blender scenes. Real datasets use intrinsic matrices with focal lengths and a principal point. We provide the intrinsic camera matrix `K` for the full-resolution images; you will need to scale them to fit the 1K images.
2. That should be correct.

By the way, you can also use our dataset with Nerfstudio, which includes download code for the JPEG-1K versions, which also scales the intrinsic camera matrices.

**Comment by Ahmedhasssan** [comment]
Hi, 
Thank you so much for your reply. 

In the description, you mentioned that the Colmap has been added for each scene to support GS. But I don't see it in the image scene folders.

Have you already added it or are you planning to add it?

Thanks

**Comment by cr333** [comment]
Please look under [`apartment/colmap`](https://fb-baas-f32eacb9-8abb-11eb-b2b8-4857dd089e15.s3.amazonaws.com/EyefulTower/apartment/colmap/index.html), for example.
